(a) Try out the programs in Part2 of the replit code.

main.py

In [ ]:
no1 = 56
no2 = 62.5
condition1 = True
condition2 = False
name1 = "SLIIT"
name2 = 'Shakya'


print(no1)
print(type(no1))

print(no2)
print(type(no2))

print(condition1)
print(type(condition1))

print(condition2)
print(type(condition2))

print(name1)
print(type(name1))

print(name2)
print(type(name2))

no4 = no1
print(no4)
print(type(no4))

age = 42
AGE = 12
Age = 10
print(age)
print(AGE)
print(Age)


number = 42
name = "Shakya"
print("Your number is ",number ," and your name is Shakya.")


x = input("Input your name : ")
print("Your name is ",x,".")

n = int(input("Enter a number : "))
m = float(input("Enter the 2nd number : "))
print(n)
print(m)

print(max(1,2,3,4,5,0))

print(min(3,5,2,1,8))

56
<class 'int'>
62.5
<class 'float'>
True
<class 'bool'>
False
<class 'bool'>
SLIIT
<class 'str'>
Shakya
<class 'str'>
56
<class 'int'>
42
12
10
Your number is  42  and your name is Shakya.
Input your name : Shakya
Your name is  Shakya .
Enter a number : 25
Enter the 2nd number : 21
25
21.0
5
1

Activity1.py

In [ ]:
value1 = int(input("Enter value 1 : "))
value2 = int(input("Enter value 2 : "))
value3 = int(input("Enter value 3 : "))

print("Maximum value is ",max(value1,value2,value3),".")
print("Minimum value is ",min(value1,value2,value3),".")

Enter value 1 : 2
Enter value 2 : 52
Enter value 3 : 3
Maximum value is  52 .
Minimum value is  2 .

Activity2.py

In [ ]:
x = float(input("Enter the width : "))
y = float(input("Enter the length : "))

Area = x * y
Perimeter = (2 * x) + (2 * y)

print("Area = ",Area)
print("Perimeter = ",Perimeter)

Enter the width : 12
Enter the length : 20
Area =  240.0
Perimeter =  64.0

Selection_Example.py

In [ ]:
length = float(input("Enter the length : "))
width = float(input("Enter the width : "))

if length == width :
    print("It is a Square.")

else :
    print("It is a Rectangle.")

Enter the length : 52
Enter the width : 32
It is a Rectangle.

Activity3.py

In [ ]:
year = int(input("Enter the year of birth : "))

dif = 2024 - year

if dif < 18 :
    print("Child")

else :
    print("Adult")

Enter the year of birth : 2010
Child

Repetition_Example.py

In [ ]:
number = 1

while number<=100 :
    print(number)
    number = number + 1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

Actitvity4.py

In [ ]:
i = 1
sum = 0

while i <=10 :
    number = int(input("Enter number : "))
    sum = sum + number
    i = i + 1

print("Sum = ",sum)

Enter number : 23
Enter number : 10
Enter number : 10
Enter number : 0
Enter number : 20
Enter number : 10
Enter number : 0
Enter number : 30
Enter number : 45
Enter number : 100
Sum =  248

Activity5.py

In [ ]:
def Average(marks1,marks2,marks3):
    Avg = (marks1+marks2+marks3)/3
    return Avg


marks1 = int(input("Enter marks of subject 1 :"))
marks2 = int(input("Enter marks of subject 2 :"))
marks3 = int(input("Enter marks of subject 3 :"))

print(Average(marks1,marks2,marks3))

Enter marks of subject 1 :25
Enter marks of subject 2 :85
Enter marks of subject 3 :100
70.0

Activity6.py

In [ ]:
fact = int(input("Enter a number :"))


def Fac(factorial) :
    result = 1
    while factorial >= 1 :
            result = result * factorial
            factorial = factorial - 1
    return result


print("Factorial of ",fact," is ",Fac(fact))

Enter a number :5
Factorial of  5  is  120

b) Create a python program to input marks of 10 students and print the maximum mark, minimum mark and average mark of the students.

In [2]:
i = 0
summation = 0
myList = []

# input marks of 10 students
while i < 10:
    marks = int(input("Enter the marks for student{}: ".format(i + 1)))
    myList.append(marks)
    summation = summation + marks
    i = i + 1

# calculate max, min, and average marks of 10 students
maximum_mark = max(myList)
minimum_mark = min(myList)
avrg = summation / 10

# display max, min, and average marks of 10 students
print("Maximum mark = ", maximum_mark)
print("Minimum mark = ", minimum_mark)
print("Average mark = ", avrg)

Enter the marks for student1: 100
Enter the marks for student2: 25
Enter the marks for student3: 87
Enter the marks for student4: 45
Enter the marks for student5: 67
Enter the marks for student6: 91
Enter the marks for student7: 53
Enter the marks for student8: 68
Enter the marks for student9: 90
Enter the marks for student10: 72
Maximum mark =  100
Minimum mark =  25
Average mark =  69.8

c)Create a program to input five marks of a student and display the grades.

• Mark > 75 – A

• Mark 65 to 75 – B

• Mark 55 to 64 – C

• Mark 45 to 54 – S

• Mark < 45 – F

In [ ]:
i = 0

while i<5:
    marks = int(input("Enter the marks of the students : "))

    if marks>=75 :
        print("Grade=A")
    elif 65<= marks <75:
        print("Grade=B")
    elif 55 <= marks <65:
        print("Grade=C")
    elif 45 <= marks < 55:
        print("Grade=S")
    elif marks<45:
        print("Grade=F")
    else:
        print("You entered marks are invalid!")

    i = i + 1

Enter the marks of the students : 12
Grade=F
Enter the marks of the students : 85
Grade=A
Enter the marks of the students : 65
Grade=B
Enter the marks of the students : 52
Grade=S
Enter the marks of the students : 60
Grade=C

d)  Write a program to input a series of numbers terminated by -999. Calculate and print the sum of the numbers entered.

In [ ]:
i = 0
sum = 0

while True:
    number = int(input("Enter a number:"))
    if number== -999:
        break
    sum = sum + number

    i = i + 1

print("Sum = ",sum)

Enter a number:12
Enter a number:3
Enter a number:45
Enter a number:123
Enter a number:25
Enter a number:-999
Sum =  208